version: "3.7"
services:

  db:
    image: postgres:17
    hostname: db
    environment:
      POSTGRES_DB: syngrapha_db
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432"
    expose:
      - "5432"
    networks:
      - syngrapha_main_net
    volumes:
      - pgdata:/var/lib/postgresql/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d syngrapha_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped



networks:
  syngrapha_main_net:
    driver: bridge



volumes:
  pgdata:
