"""
add_iat

Revision ID: 85891e06cc73
Revises: a3f09a2be3f2
Create Date: 2025-06-05 11:52:13.785143

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.sql.functions import current_timestamp

# revision identifiers, used by Alembic.
revision: str = "85891e06cc73"
down_revision: str | None = "a3f09a2be3f2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tokens", sa.Column(
            "issued_at", sa.DateTime(), nullable=False,
            server_default=current_timestamp()
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tokens", "issued_at")
    # ### end Alembic commands ###
