"""
initial

Revision ID: a3f09a2be3f2
Revises: 
Create Date: 2025-06-04 19:24:09.514795

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a3f09a2be3f2"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("hashed_pass", sa.String(), nullable=False),
        sa.Column("phone_number", sa.String(), nullable=False),
        sa.Column("nalog_access_token", sa.String(length=256), nullable=True),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("username")
    )
    op.create_table(
        "tokens",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token", sa.String(length=256), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.uuid"] ),
        sa.PrimaryKeyConstraint("token")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tokens")
    op.drop_table("users")
    # ### end Alembic commands ###
